"""initial schema

Revision ID: 971803a783a5
Revises: 
Create Date: 2026-08-13 15:21:28.279246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '971803a783a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TABLES = (
    'reconciliation_jobs',
    'chat_sessions',
    'transactions',
    'agent_actions',
    'chat_messages',
    'matches',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bank_pdf_path', sa.Text(), nullable=False),
    sa.Column('ledger_pdf_path', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('queued', 'processing', 'extracting', 'matching', 'completed', 'failed')", name=op.f('ck_reconciliation_jobs_valid_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_jobs'))
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('active_job_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['active_job_id'], ['reconciliation_jobs.id'], name=op.f('fk_chat_sessions_active_job_id_reconciliation_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('reference_number', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('bank', 'ledger')", name=op.f('ck_transactions_valid_source')),
    sa.ForeignKeyConstraint(['job_id'], ['reconciliation_jobs.id'], name=op.f('fk_transactions_job_id_reconciliation_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['reconciliation_jobs.id'], name=op.f('fk_agent_actions_job_id_reconciliation_jobs')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_agent_actions_session_id_chat_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_actions'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('system', 'user', 'assistant', 'tool')", name=op.f('ck_chat_messages_valid_role')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('bank_transaction_id', sa.UUID(), nullable=False),
    sa.Column('ledger_transaction_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_type in ('exact', 'fuzzy', 'manual')", name=op.f('ck_matches_valid_match_type')),
    sa.CheckConstraint("status in ('matched', 'under_review', 'reconciled', 'rejected')", name=op.f('ck_matches_valid_status')),
    sa.CheckConstraint('confidence_score >= 0 and confidence_score <= 100', name=op.f('ck_matches_valid_confidence_score')),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['transactions.id'], name=op.f('fk_matches_bank_transaction_id_transactions')),
    sa.ForeignKeyConstraint(['job_id'], ['reconciliation_jobs.id'], name=op.f('fk_matches_job_id_reconciliation_jobs')),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['transactions.id'], name=op.f('fk_matches_ledger_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    for table in TABLES:
        op.execute(f'alter table {table} enable row level security')
        op.execute(f'revoke all on table {table} from anon, authenticated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    op.drop_table('chat_messages')
    op.drop_table('agent_actions')
    op.drop_table('transactions')
    op.drop_table('chat_sessions')
    op.drop_table('reconciliation_jobs')
    # ### end Alembic commands ###
